### ISSUE TITLE
Spacebar and Left Mouse shoot at the same time

### ISSUE THREAD

**Issue by FranciscoKnebel** [FranciscoKnebel/spaceinvader#1]
Non-Intended, needs a lock variable, so you can only shoot with one at a time.
In later levels, maybe you could use both, so the levels become easier?

## Further detailing
You can smash both buttons at the same time, creating a stream with double the amount of shoots it would fire if the default behavior was being used. Spacebar and Left mouse shooting should be considered alternative controls, not separate entities.

A lock between these buttons should be created, so you can't use both at the same time.
A future implementation could add this shooting behavior as an upgrade to the shooting mechanisms.

**Comment by CrowsVeldt** [comment]
I'll give it a try

**Comment by CrowsVeldt** [comment]
I haven't managed to reproduce the issue so far, it seems to be working as intended.

**Comment by FranciscoKnebel** [comment]
Hello @CrowsVeldt, thanks for taking an interest in this issue. I'll update the description to detail this issue more. If you have any doubts, feel free to ask.

**Comment by CrowsVeldt** [comment]
Thanks. I'll try to take a look at it again tomorrow.

**Comment by FranciscoKnebel** [comment]
@CrowsVeldt I added more details. If you are going to give it a try, please fork the development branch and feel free to submit a PR anytime :+1:
